version: "3.5"
services:

  vuesonicfe:
    image: nginx:alpine
    container_name: vuesonic-frontend
    restart: always
    working_dir: /application
    volumes:
      - ./logs/nginx:/var/log/nginx
      - ./dist:/application
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "4020:80"
